server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    max-threads: 800
    max-connections: 20000
    max-swallow-size: -1

redis:
  script:
    path: unlock.lua
redisson:
  url: "redis://127.0.0.1:6379"
  password:

spring:
  redis:
    #单机配置如下，database默认为0，可不配置
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100000ms
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数
        max-idle: 10      # 连接池最大空闲连接
        min-idle: 5       # 连接池最小空闲连接
        max-wait: -1ms    # 连接池最大阻塞时间
